menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Mathematical Analysis', url: 'vector-calculus'}
- {name: 'Fractional Calculus', url: 'quantum-mechanics'}

contacts:
- {name: 'Prof. Maamar Benbachir', title: 'Professor', institution: 'National Higher School of Mathematics', institution_address: 'Algiers, Algeria', phone: '(000) 000-0000', email: 'mbenbachir2001@gmail.com ', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
